#!/bin/bash

read -d'' -u0 stdin

if test -d /var/lib/git/%{REPO}.git/hooks/post-update.d; then
  /bin/run-parts --regex '\.sh$' --list /var/lib/git/%{REPO}.git/hooks/post-update.d | while read s; do
    echo $s >/dev/stderr
    echo "$stdin" | $s
  done
fi
